"""empty message

Revision ID: 48fb02473c1c
Revises: 55031bcee1e7
Create Date: 2023-02-23 01:21:59.038984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fb02473c1c'
down_revision = '55031bcee1e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_discontinued', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('date_discontinued')

    # ### end Alembic commands ###
