"""empty message

Revision ID: 670f6efa3743
Revises: c08556927ef8
Create Date: 2023-02-24 23:18:52.334005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '670f6efa3743'
down_revision = 'c08556927ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', mysql.DECIMAL(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###
